name: Push main

on:
  push:
    branches: [main]

jobs:
  test:
    uses: ./.github/workflows/test-and-build.yml
    with:
      ref: ${{ github.ref }}
    secrets: inherit

  pre-commit:
    uses: ./.github/workflows/pre-commit.yml
    with:
      ref: ${{ github.ref }}
    secrets: inherit
